##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby


##########################################################################
##
##    Load Modules
##

load  File.expand_path('common/CommonCustomize.rb')
load  File.expand_path('common/AttachSCSIHdd.rb')

load  File.expand_path('common/UploadFiles.rb')
load  File.expand_path('common/SetupCentos.rb')
load  File.expand_path('common/RamDisk.rb')
load  File.expand_path('common/SetupUsers.rb')


##########################################################################
##
##    Configuration
##

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/rocky9-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-rocky9-develop"
    v.memory = "3072"
    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 15022, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.50")
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end


##########################################################################
##
##    Customize Virtual Machine
##


disk_image_file = File.expand_path('./disk/rocky9-develop-sdb.vdi')

Vagrant.configure("2") do |config|

  # Common Customize.
  customize_config(config)
  config.vm.provider "virtualbox" do |v|
    customize_vm_provider(v)
  end

  # Attach Disk.
  config.vm.provider "virtualbox" do |vb|
    add_scsi_storage_controller(vb)
    attach_scsi_hdd(vb, disk_image_file)
  end
  provision_newhdd_scsi(config.vm, dev: '/dev/sdb')
  config_detach_trigger(config)

  # Provisioning(s)
  provision_upload_files(config.vm)
  provision_setup_centos(config.vm)
  provision_ram_disk(config.vm)
  provision_setup_users(config.vm)

end
