##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby


##########################################################################
##
##    Load Modules
##

load  File.expand_path('common/CommonCustomize.rb')
load  File.expand_path('common/AttachIDEHdd.rb')

load  File.expand_path('common/UploadFiles.rb')
load  File.expand_path('common/SetupCentos.rb')
load  File.expand_path('common/RamDisk.rb')
load  File.expand_path('common/SetupUsers.rb')


##########################################################################
##
##    Configuration
##

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/rocky9-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-centos7-develop"
    v.memory = "3072"
    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 15022, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.50")
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end


##########################################################################
##
##    Customize Virtual Machine
##

# Common Customize.

Vagrant.configure("2") do |config|
  customize_config(config)
  config.vm.provider "virtualbox" do |v|
    customize_vm_provider(v)
  end
end

# Attach Disk.
disk_image_file = File.expand_path('./disk/rocky9-develop-sdb.vdi')

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    attach_ide_hdd(v, disk_image_file)
  end
  provision_newhdd_ide(config.vm)
  config_detach_trigger(config)
end

# Provisioning(s)

Vagrant.configure("2") do |config|
  provision_upload_files(config.vm)
end

Vagrant.configure("2") do |config|
  provision_setup_centos(config.vm)
end

Vagrant.configure("2") do |config|
  provision_ram_disk(config.vm)
end

Vagrant.configure("2") do |config|
  provision_setup_users(config.vm)
end
